# Generated by Django 3.0.4 on 2020-03-24 03:36

from django.db import migrations, models
import django.db.models.deletion
import sidewinder.identity.models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('client_id', models.CharField(max_length=14)),
                ('client_secret', models.CharField(max_length=27)),
            ],
            options={
                'verbose_name': 'Reddit Application',
                'verbose_name_plural': 'Reddit Applications',
            },
        ),
        migrations.AddField(
            model_name='redditcredentials',
            name='app',
            field=models.ForeignKey(default=sidewinder.identity.models.RedditApplication.singleton_instance_id, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='identity.RedditApplication'),
        ),
    ]
