# Generated by Django 4.0.3 on 2023-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_redditapplication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditapplication',
            name='client_id',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='redditapplication',
            name='client_secret',
            field=models.CharField(max_length=30),
        ),
    ]
