# Generated by Django 4.0.3 on 2023-04-22 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_increase_client_id_secret_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('client_id', models.CharField(max_length=20)),
                ('client_secret', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Discord Application',
                'verbose_name_plural': 'Discord Applications',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, verbose_name='Discord ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='redditcredentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiscordCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('last_refresh', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord Credentials',
                'verbose_name_plural': 'Discord Credentials',
            },
        ),
    ]
