# Generated by Django 3.0.4 on 2020-04-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=100)),
                ('total_actions', models.IntegerField()),
            ],
            options={
                'verbose_name': 'science log',
                'verbose_name_plural': 'science logs',
            },
        ),
    ]
