# Generated by Django 3.0.4 on 2020-04-02 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sneknet', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snek_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
