# Generated by Django 3.0.4 on 2020-04-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('sneknet', '0004_masterswitch'), ('sneknet', '0005_masterswitch_additions'), ('sneknet', '0006_masterswitch_enable_five_human_hiding'), ('sneknet', '0007_delete_masterswitch')]

    dependencies = [
        ('sneknet', '0003_token_owner'),
    ]

    operations = [
    ]
