# Generated by Django 3.0.4 on 2020-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneknet', '0004_masterswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterswitch',
            name='disable_unauthorized_queries',
            field=models.BooleanField(default=False, help_text='Tick this box to disable any requests to /query that are missing a valid token'),
        ),
        migrations.AddField(
            model_name='masterswitch',
            name='enable_imposter_flipping',
            field=models.BooleanField(default=True, help_text='Enable overwriting of imposter-tagged messages to human if we get a conflicting report'),
        ),
    ]
