# Generated by Django 3.0.4 on 2020-04-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneknet', '0005_masterswitch_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterswitch',
            name='enable_five_human_hiding',
            field=models.BooleanField(default=False, help_text="Enable to cause the /query endpoint to lie if it's going to return 5 incorrect answers"),
        ),
    ]
