# Generated by Django 3.0.4 on 2020-04-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneknet', '0006_masterswitch_enable_five_human_hiding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterSwitch',
        ),
    ]
