# Generated by Django 3.0.4 on 2021-04-02 03:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.IntegerField(default=0)),
                ('first_count', models.IntegerField(default=0)),
                ('second_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0, verbose_name='Current win streak')),
                ('losses', models.IntegerField(default=0)),
                ('last_was_win', models.BooleanField(default=False, verbose_name='Last vote was a win?')),
                ('last_active', models.DateTimeField(db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('current_channel', models.CharField(default=None, max_length=512, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_streaks', models.BooleanField(default=False, help_text='Whether to prefer long streaks or mix.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
