# Generated by Django 3.0.4 on 2020-10-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeGameServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.PositiveIntegerField(default=10, help_text='The maximum number of players that can join the snake game')),
            ],
            options={
                'verbose_name': 'Snake Game Server',
                'verbose_name_plural': 'Snake Game Servers',
            },
        ),
    ]
