# Generated by Django 3.0.4 on 2020-10-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakegame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakegameserver',
            name='arena_height',
            field=models.PositiveIntegerField(default=30, help_text='The height of the arena', verbose_name='Arena Height'),
        ),
        migrations.AddField(
            model_name='snakegameserver',
            name='arena_width',
            field=models.PositiveIntegerField(default=40, help_text='The width of the arena', verbose_name='Arena Width'),
        ),
        migrations.AddField(
            model_name='snakegameserver',
            name='food_amount',
            field=models.PositiveIntegerField(default=1, help_text='The amount of food to keep on screen at any given time', verbose_name='Food Amount'),
        ),
        migrations.AddField(
            model_name='snakegameserver',
            name='food_score',
            field=models.PositiveIntegerField(default=1, help_text='The score and amount of segments that a player gets when they eat food', verbose_name='Food Score'),
        ),
        migrations.AddField(
            model_name='snakegameserver',
            name='initial_segments',
            field=models.PositiveIntegerField(default=4, help_text='The amount of segments that a player should start with', verbose_name='Initial Segments'),
        ),
        migrations.AddField(
            model_name='snakegameserver',
            name='max_segments',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The maximum amount of segments that any given player can have', null=True, verbose_name='Maximum Segments'),
        ),
        migrations.AlterField(
            model_name='snakegameserver',
            name='max_players',
            field=models.PositiveIntegerField(default=10, help_text='The maximum number of players that can join the snake game', verbose_name='Maximum Players'),
        ),
    ]
