# Generated by Django 3.0.4 on 2020-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnownAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, unique=True)),
                ('correct', models.BooleanField()),
                ('seen_times', models.PositiveIntegerField(default=0, verbose_name='times seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Known Answer',
                'verbose_name_plural': 'Known Answers',
            },
        ),
    ]
