# Generated by Django 3.0.4 on 2020-04-02 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imposter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownanswer',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
