# Generated by Django 3.0.4 on 2020-04-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imposter', '0002_knownanswer_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownanswer',
            name='submission_tag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
