# Generated by Django 3.0.4 on 2020-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imposter', '0003_knownanswer_submission_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownanswer',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
