# Generated by Django 3.0.4 on 2020-04-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imposter', '0004_knownanswer_question_number'),
    ]

    operations = [
        migrations.RunSQL(
            sql=r'CREATE INDEX imposter_knownanswer_upper_message ON imposter_knownanswer (UPPER(message));',
            reverse_sql=r'DROP INDEX "imposter_knownanswer_upper_message";'
        ),
    ]
