# Generated by Django 3.0.4 on 2020-04-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imposter', '0004_knownanswer_message_upperindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_all', models.BooleanField(default=True)),
                ('enable_queries', models.BooleanField(default=True)),
                ('enable_imposter_flipping', models.BooleanField(default=True, help_text='Enable overwriting of imposter-tagged messages to human if we get a conflicting report')),
                ('enable_five_human_hiding', models.BooleanField(default=False, help_text="Enable to cause the /query endpoint to lie if it's going to return 5 incorrect answers")),
                ('disable_unauthorized_queries', models.BooleanField(default=False, help_text='Tick this box to disable any requests to /query that are missing a valid token')),
                ('question_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Master Switches',
                'verbose_name_plural': 'Master Switches',
            },
        ),
    ]
