# Generated by Django 4.0.3 on 2022-03-27 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('high_priority', models.BooleanField(help_text='Gives the project special priority - shown to unauthenticated users, has a higher chance of being picked', verbose_name='High Priority')),
                ('users', models.ManyToManyField(blank=True, related_name='place_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDivision',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(help_text='Lower is better')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.project')),
            ],
        ),
    ]
