# Generated by Django 4.0.3 on 2022-03-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_user_count',
            field=models.BooleanField(default=True, help_text='Whether to publicly show the number of users joined to this project', verbose_name='Show User Count'),
        ),
    ]
