# Generated by Django 4.0.3 on 2022-03-30 21:22

import april.place.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_project_show_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdivision',
            name='content',
            field=models.BinaryField(default=april.place.models.default_division_bytes, help_text='Image data'),
        ),
    ]
