# Generated by Django 4.0.3 on 2023-03-15 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0005_canvassettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='place_management', to=settings.AUTH_USER_MODEL),
        ),
    ]
