# Generated by Django 4.0.3 on 2023-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdivision',
            name='division_name',
            field=models.CharField(default='testDivision', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdivision',
            name='priority',
            field=models.IntegerField(help_text='A higher number receives priority'),
        ),
    ]
