# Generated by Django 4.0.3 on 2023-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_remove_project_managers_remove_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=7),
        ),
    ]
